### ISSUE TITLE
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'

### ISSUE THREAD

**Issue by zhuguiqian** [intel/intel-extension-for-pytorch#190]
install intel_extension_for_pytorch by command "python -m pip install torch_ipex==1.9.0 -f https://software.intel.com/ipex-whl-stable" on Cooper Lake successfully.
can find "torch-ipex 1.9.0" by pip list.
but 
import intel_extension_for_pytorch as ipex
report ModuleNotFoundError: No module named 'intel_extension_for_pytorch'

**Comment by zhuguiqian** [comment]
> We do not upload the ipex library to pip because of the image size limitation. Regarding the `intel_extension_for_pytorch` package name, it is for 1.10. If you try the 1.9.0, please refer to https://github.com/intel/intel-extension-for-pytorch/tree/xpu-cpu. The difference is the package name. Regarding 1.9.0, the package name is `intel_pytorch_extension` while the 1.10 is `intel_extension_for_pytorch`. The package name evolution is because of legal requirements. The 1.10 package name is as same as the project name.

thanks for reply.
 
i use "import intel_pytorch_extension", report Sefmentation fault error

![image](https://user-images.githubusercontent.com/7693110/139614105-d25db0c7-eaab-4aa2-8c6c-9dac16d4cd2e.png)

**Comment by EikanWang** [comment]
Could you please try the release/1.10 branch?

**Comment by EikanWang** [comment]
I suppose this issue has been fixed on release/1.10 branch. Please feel free to reopen it if not.

**Comment by maulberto3** [comment]
Hi, just now I've been having trouble installing from pip: `ERROR: No matching distribution found for intel_pytorch_extension`

**Comment by ZailiWang** [comment]
Hi @maulberto3 , ipex package name has been changed since 1.10, please try with this command:
**python -m pip install intel_extension_for_pytorch==1.12.1 -f https://developer.intel.com/ipex-whl-stable**

**Comment by maulberto3** [comment]
Hi again @EikanWang still no luck, this time it says SSL error, after a 5 default retries, it couldn't connect to the website.

**Comment by ZailiWang** [comment]
Hi @maulberto3 sorry the version should be '1.12.100' rather than '1.12.1'. Would you please try the cammand
python -m pip install intel_extension_for_pytorch==1.12.100 -f https://developer.intel.com/ipex-whl-stable

But with the previous command you should get a "No matching distribution found" error but not "SSL error". If with the '1.12.100' command the problem remains, would you please share some more info? (like your server environment, network setup, how PyTorch was installed, etc.)

**Comment by maulberto3** [comment]
Hi @EikanWang attached image, Windows 10, fresh new python venv, no previous packages, no SSL error, python 3.10. Doesn't work either directly from Pypi. 
![oneapi_pic](https://user-images.githubusercontent.com/22672781/199636856-aaab6298-ebb9-4f73-af33-9be35672139d.png)

**Comment by ZailiWang** [comment]
Hi @maulberto3 Currently ipex doesn't have Windows system support yet. Sorry for the inconvenience.
For windows systems users, we recommend to utilize ipex in WSL/WSL2 (Windows Subsystem for Linux) for functionality verification. Performance might be inferior compared with native Linux system.

**Comment by Mhbuur** [comment]
@ZailiWang do you know when we can expect windows support? I´m running into the same issue here, tried several different versions

**Comment by jingxu10** [comment]
On Windows, would you run it in WSL2? Thank you.

**Comment by jgong5** [comment]
> On Windows, would you run it in WSL2? Thank you.

@Mhbuur Yep, just wanted to know if WSL2 is acceptable for your case or native Windows support is required.

**Comment by Mhbuur** [comment]
@jingxu10 @jgong5 native Windows support is preferable, as I'm not working with WSL2 in any other contexts at the moment.

**Comment by Vipitis** [comment]
would also like native Windows support

**Comment by jgong5** [comment]
Thanks for the feedbacks @Mhbuur @Vipitis . I'd like to learn more about the requirements about the Windows support you are looking for. Would you please share more about the use cases (if you are ok to share), e.g., the models/tasks, data types, inference or training, latency requirement, CPU types etc.?

**Comment by Vipitis** [comment]
I got an Arc A750 and replaced my older nvidia card. It would be fantastic if it just worked as a drop in replacement any a single line of code to automatically set the device to xpu if available, like you do with cuda. I am willing to put in more effort but I do really want to write device agnostic code that can work on cpu, cuda or intel gpu, as I plan to publish scripts to reproducibility The models I actually run are usually language models from huggingface for inference and some fine tuning. Additionally I work on a shared tasks that uses CLIP, so I would love to accelerate model inference. It's in a university research setting to there are no requirements for specific performance, as long as it's faster than relying on CPU. CPU is kinda irrelevant in that case as I am still on a consumer Skylake platform but seek to upgrade soon.

I hope that helps, as for a request on the side: perhaps add OS requirements to the readme or documentation.

**Comment by abymmathew-mli** [comment]
I am not seeing the 2.0.0 version of intel_extension_for_pytorch.
https://www.intel.com/content/dam/develop/external/us/en/documents/ipex/whl-stable-xpu.html

I have pytorch 2.0.0 python 3.11.0 and as per the table, it should be using the intel extension 2.0.0 which is not in the repository.
https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/installation.html

When would it be available?

**Comment by shuaishuaigu** [comment]
> Hi @EikanWang attached image, Windows 10, fresh new python venv, no previous packages, no SSL error, python 3.10. Doesn't work either directly from Pypi (not shown in image). ![oneapi_pic](https://user-images.githubusercontent.com/22672781/199636856-aaab6298-ebb9-4f73-af33-9be35672139d.png)

i have same problem, are you solve it now? please share it how to solve it problem

**Comment by shuaishuaigu** [comment]
> Hi @EikanWang attached image, Windows 10, fresh new python venv, no previous packages, no SSL error, python 3.10. Doesn't work either directly from Pypi (not shown in image). ![oneapi_pic](https://user-images.githubusercontent.com/22672781/199636856-aaab6298-ebb9-4f73-af33-9be35672139d.png)

i have same problem, are you solve it now? please share it how to solve it problem

**Comment by jingxu10** [comment]
We haven't released the packages for Windows yet. Please run on WSL2.

**Comment by fedecompa** [comment]
Could you release the packages for Windows please? Thanks
