### ISSUE TITLE
Latest xpu-master branch compiling issue

### ISSUE THREAD

**Issue by fredlarochelle** [intel/intel-extension-for-pytorch#373]
### Describe the issue

While trying to compile the lastest `xpu-master` branch (89627affe16897b5c1a70c25892741e9be9fca1b), I get an error starting at `[4849/6323] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/Version.cpp.o` while its building PyTorch. 

Is this issue temporary and related to the ongoing rebase to PyTorch 2.0 or should I be able to build IPEX without issues?

Here is the [build.log](https://github.com/intel/intel-extension-for-pytorch/files/11780570/build.log).

**Comment by gujinghui** [comment]
Looks like the issue is caused by mismatching btw ideep and oneDNN in CPU side?


```
/home/fred/ipex_bundle/pytorch/third_party/ideep/include/ideep/attributes.hpp: In constructor ‘ideep::attr_t::attr_t(int, const scale_t&)’:
/home/fred/ipex_bundle/pytorch/third_party/ideep/include/ideep/attributes.hpp:20:5: error: ‘set_output_scales’ was not declared in this scope; did you mean ‘get_output_scales’?
   20 |     set_output_scales(mask, scales);
      |     ^~~~~~~~~~~~~~~~~
```

**Comment by ZhaoqiongZ** [comment]
Hi @fredlarochelle , could you try to compile by following this tutorial and use the compile_bundle.sh script to compile both torch/torchvision/torchaudio/intel_extension_for_pytorch https://github.com/intel/intel-extension-for-pytorch/blob/xpu-master/docs/tutorials/installation.md#install-via-compiling-from-source  , I just verified that it works with latest xpu-master branch.

**Comment by fcharras** [comment]
I get the following error at the beginning of the last step (`ipex` compilation):

```
-- Performing Test SYCL_FLAG_SUPPORTED - Failed
CMake Error at third_party/oneDNN/cmake/dpcpp_driver_check.cmake:36 (message):
  IntelLLVM doesn't support -fsycl flag.
Call Stack (most recent call first):
  third_party/oneDNN/cmake/dpcpp_driver_check.cmake:60 (CHECK_COMPILER_DRIVER)
  third_party/oneDNN/cmake/SYCL.cmake:30 (include)
  third_party/oneDNN/CMakeLists.txt:118 (include)
```

**Comment by fredlarochelle** [comment]
@ZhaoqiongZ I followed that tutorial precisely, and I have previously build IPEX multiple time without any problems. Hence, it wasn't the cause for this issue.

Fortunately, I was able to successfully build using the latest `xpu_master` branch (b7412a424a7f4cf048efcf4c20fabd9b311ae369). It appears that the problem has been resolved by one of the recent commit.

Although my issue has been resolved, I will keep this thread open as @fcharras is currently facing some difficulties of their own.

**Comment by fcharras** [comment]
It works again for me too. (with the exception of the `$LIBRARY_PRELOAD` variable lookup that seems for some reason caused an error if it's not defined.. :thinking: but I could manually fix the script ). Presumably I did mistakes when trying to skip torchvision and torchaudio previously by commenting relevant blocks. Or something else with environment setup. :thinking: It would be nice having nightly binaries for supported gpus.

**Comment by martinmCGG** [comment]
Confirmed the build still fails. I hit different errors when building the current IPEX (at the step when building PyTorch):

    /ipex_build/pytorch/third_party/ideep/include/ideep/operators/inner_product.hpp:758:11: error: no matching function for call to ‘dnnl::inner_product_backward_weights::primitive_desc::primitive_desc(<brace-enclosed initializer list>, ideep::attr_t&, const ideep::engine&, dnnl::inner_product_forward::primitive_desc&)’
    /ipex_build/pytorch/third_party/ideep/include/ideep/operators/matmul.hpp:871:16: error: no matching function for call to ‘dnnl::matmul::primitive_desc::primitive_desc(<brace-enclosed initializer list>, ideep::attr_t&, const ideep::engine&)’`
    /ipex_build/pytorch/third_party/ideep/include/ideep/operators/matmul.hpp:869:31: error: cannot convert ‘ideep::matmul_forward::do_prepare<false>(ideep::matmul_forward_params&, const ideep::tensor&, const ideep::tensor&, const ideep::tensor&, ideep::tensor&, float, float, const ideep::attr_t&, ideep::data_type, const ideep::engine&)::<lambda()>’ to ‘const std::function<dnnl::matmul::primitive_desc()>&’

All these seem to be related to DNNL's `primitive_desc` - perhaps something changed upstream and broke the patches? I will try looking into it soon.

Replicable with running `docker build -t ipex .` in the same directory as the following `Dockerfile`:
```
FROM intel/oneapi-basekit:2023.1.0-devel-ubuntu22.04
RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install python-is-python3 libpng-dev libjpeg-dev python3-pip
WORKDIR /ipex_build
RUN wget https://github.com/intel/intel-extension-for-pytorch/raw/xpu-master/scripts/compile_bundle.sh
RUN bash compile_bundle.sh /opt/intel/oneapi/compiler/latest /opt/intel/oneapi/mkl/latest
```
Docker is used to ensure a clean and well-defined environment, but I saw the `primitive_desc` error also when building the [previously working](https://github.com/intel/intel-extension-for-pytorch/issues/373#issuecomment-1601571064) commit b7412a4 by setting `VER_IPEX="b7412a424a7f4cf048efcf4c20fabd9b311ae369"` in `compile_bundle.sh`. (This was in Ubuntu on top of WSL2.)

If it's a user error (my first time building PyTorch+IPEX+etc.), I would be grateful for a hint, or just a pointer that it works for someone else.

**Comment by ZailiWang** [comment]
Hi @martinmCGG thanks for reporting this. I have root caused this and the fix is WIP. Actually it's caused by version conflict between oneDNN in activated oneAPI env and PyTorch default dependent oneDNN.

**Comment by martinmCGG** [comment]
Thank you @ZailiWang, for the suggestions. The environment variables I set earlier (in my case already in .bashrc) were really the cause. I just successfully built 5f19e5c0873bd886d8e8926a0b0755ad3bf1f719 without setting the oneAPI environment before build. (That was in WSL2 Ubuntu 22.04; I only had to `export LD_LIBRARY_PATH=''` before running the script as it was undefined in my environment and the script complained [here](https://github.com/intel/intel-extension-for-pytorch/blob/5f19e5c0873bd886d8e8926a0b0755ad3bf1f719/scripts/compile_bundle.sh#L139).)

A few ideas to avoid possible future confusion: it would be nice if CMake preferred the "repo-provided" oneDNN library, or if there was a detection of incompatible API version in the C++ code that uses oneDNN (ideep?). Alternatively, adding a note to the [build documentation](https://github.com/intel/intel-extension-for-pytorch/blob/xpu-master/docs/tutorials/installation.md#compile-the-bundle-pytorch-torchvision-torchaudio-intel-extension-for-pytorch-with-script) might be useful for other users, e.g. "oneAPI environment variables (`intel/oneapi/setvars.sh`) should NOT be set when running the `compile_bundle.sh` script to make sure the compatible versions of oneAPI libraries like oneDNN shipped/downloaded with PyTorch are used."

It's good to hear that once the [upstream PR](https://github.com/pytorch/pytorch/pull/97957) is accepted, the build should work even with the current oneDNN installed system-wide.

**Comment by Wovchena** [comment]
Hi. I got similar error while running `./scripts/compile_bundle.sh /opt/intel/oneapi/dpcpp-ct/2023.2.0/ /opt/intel/oneapi/mkl/2023.2.0/ -fsycl-targets=spir64_gen -Xs "-device adl-s"` at commit 5af6dbb3f9bccc4e20d673c40673e64ea63bd490

```
In file included from /opt/intel/oneapi/dnnl/2023.2.0/cpu_dpcpp_gpu_dpcpp/include/oneapi/dnnl/dnnl.hpp:23,                                                                                                                                        
                 from /opt/intel/oneapi/dnnl/2023.2.0/cpu_dpcpp_gpu_dpcpp/include/dnnl.hpp:20,                                                                                                                                                    
                 from /home/wov/r/intel-extension-for-pytorch/scripts/pytorch/aten/src/ATen/Version.cpp:9:                                                                                                                                        
/home/wov/r/intel-extension-for-pytorch/scripts/pytorch/build/third_party/ideep/mkl-dnn/third_party/oneDNN/include/oneapi/dnnl/dnnl_config.h:73:2: error: #error "Unexpected DNNL_CPU_RUNTIME"                                                    
   73 | #error "Unexpected DNNL_CPU_RUNTIME"                                                                                                                                                                                                      
      |  ^~~~~                                                                                                                                                                                                                                    
/home/wov/r/intel-extension-for-pytorch/scripts/pytorch/build/third_party/ideep/mkl-dnn/third_party/oneDNN/include/oneapi/dnnl/dnnl_config.h:82:2: error: #error "At least one runtime must be specified"                                         
   82 | #error "At least one runtime must be specified"                                                                                                                                                                                           
      |  ^~~~~                                                                                                                                                                                                                                    
In file included from /home/wov/r/intel-extension-for-pytorch/scripts/pytorch/third_party/ideep/include/ideep/tensor.hpp:4,                                                                                                                       
                 from /home/wov/r/intel-extension-for-pytorch/scripts/pytorch/third_party/ideep/include/ideep.hpp:40,                                                                                                                             
                 from /home/wov/r/intel-extension-for-pytorch/scripts/pytorch/aten/src/ATen/Version.cpp:10:                                                                                                                                       
/home/wov/r/intel-extension-for-pytorch/scripts/pytorch/third_party/ideep/include/ideep/attributes.hpp: In constructor ‘ideep::attr_t::attr_t(int, const scale_t&)’:                                                                              
/home/wov/r/intel-extension-for-pytorch/scripts/pytorch/third_party/ideep/include/ideep/attributes.hpp:20:5: error: ‘set_output_scales’ was not declared in this scope; did you mean ‘get_output_scales’?                                         
   20 |     set_output_scales(mask, scales);                                                                                                                                                                                                      
      |     ^~~~~~~~~~~~~~~~~                                                                                                                                                                                                                     
      |     get_output_scales
```
But I can see that the mentioned https://github.com/pytorch/pytorch/pull/97957 is merged. Can you help?

**Comment by Wovchena** [comment]
I figured that out: the advice
> oneAPI environment variables (`intel/oneapi/setvars.sh`) should NOT be set when running the `compile_bundle.sh` script to make sure the compatible versions of oneAPI libraries like oneDNN shipped/downloaded with PyTorch are used.

is still applicable. But with that `compile_bundle.sh` fails while generating wheel for `intel-extension-for-pytorch`. At this point it's required to run `setvars.sh` and run what failed manually: `python setup.py clean && python setup.py bdist_wheel 2>&1 | tee build.log`.

After that the build will fail with the error described in https://github.com/intel/intel-extension-for-pytorch/issues/441. Revert https://github.com/intel/intel-extension-for-pytorch/commit/7db2f1c47495e6a26cfd212b191eb8a66524096e and run `python setup.py clean && python setup.py bdist_wheel 2>&1 | tee build.log`.

P. S. Don't forget to compile and install https://github.com/oneapi-src/level-zero

**Comment by nickp27** [comment]
Hello - I have just tried building with the latest commits in xpu-master, but am still getting the error reported in the first post i.e. from around [4849/6323] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/Version.cpp.o. It looks like https://github.com/intel/intel-extension-for-pytorch/issues/441 was directed at another error?
